version: '2'
services:
  dev-spark-1.6:
    build: .
    volumes:
      - .:/opt/sparkly/
    depends_on:
      - cassandra.docker
      - elastic.docker
      - mysql.docker
      - kafka.docker

  test-spark-1.6:
    build: .
    depends_on:
      - cassandra.docker
      - elastic.docker
      - mysql.docker
      - kafka.docker

  cassandra.docker:
    image: cassandra:2.1.13
    mem_limit: 500M
    memswap_limit: 600M
    environment:
      MAX_HEAP_SIZE: 500M
      HEAP_NEWSIZE: 200M

  elastic.docker:
    image: elasticsearch:1.7.0

  mysql.docker:
    image: mysql
    environment:
      MYSQL_DATABASE: sparkly_test
      MYSQL_USER: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

  kafka.docker:
    image: wurstmeister/kafka
    expose:
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka.docker
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper.docker:2181
    depends_on:
      - zookeeper.docker

  zookeeper.docker:
    image: wurstmeister/zookeeper
    expose:
      - "2181"
